# HTTP Configuration
quarkus.http.port=8001
quarkus.grpc.server.use-separate-server=false


# gRPC Client Configuration - Sensor Service
quarkus.grpc.clients.sensor-service.host=localhost
quarkus.grpc.clients.sensor-service.port=8000

# gRPC Client Configuration - Traffic Light Service
quarkus.grpc.clients.traffic-light-service.host=localhost
quarkus.grpc.clients.traffic-light-service.port=8003

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.mihailmerkov.sctms.traffic".level=DEBUG
